site_name: Appunti Digitalizzati

theme:
  name: material
  
  features:
  
    - search
    - awesome-pages:
      order_by: filename
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    
  language: en

  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        name: Change to dark mode
        icon: material/weather-sunny
    - scheme: slate
      primary: amber
      accent: yellow
      toggle:
        name: Change to light mode
        icon: material/weather-night

font:
  code: Roboto

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
